# Generated by Django 4.1.1 on 2022-09-22 06:16

import candidates.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0005_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='resume',
            field=models.FileField(blank=True, max_length=255, null=True, upload_to=candidates.models.upload_to, verbose_name='resume'),
        ),
    ]
