# Generated by Django 4.1.1 on 2022-09-22 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0006_alter_candidate_resume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='department',
            field=models.CharField(choices=[('IT', 'IT'), ('Sales', 'Sales'), ('Recruiting', 'Recruiting'), ('Accounting', 'Accounting'), ('Materials', 'Materials')], max_length=16),
        ),
        migrations.AlterField(
            model_name='candidate',
            name='status',
            field=models.IntegerField(choices=[('Applied', 'Applied'), ('Rejected', 'Rejected'), ('Accepted', 'Accepted')], default=0),
        ),
    ]
