# Generated by Django 4.1.1 on 2022-09-22 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('candidates', '0009_alter_candidate_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='experience_one',
        ),
        migrations.RemoveField(
            model_name='candidate',
            name='experience_two',
        ),
        migrations.AddField(
            model_name='candidate',
            name='current',
            field=models.BooleanField(null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='designation',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='end',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='organisation',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='candidate',
            name='start',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Experience',
        ),
    ]
